# Generated by Django 6.0.7 on 2026-08-05 13:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_theater_showtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='time',
        ),
        migrations.AddField(
            model_name='showtime',
            name='screen_name',
            field=models.CharField(default='Screen 1', max_length=50),
        ),
        migrations.AddField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 5, 13, 29, 17, 487256, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtime',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(default='Screen 1', max_length=50)),
                ('row', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
            ],
            options={
                'unique_together': {('screen_name', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HELD', 'Temporarily Held'), ('BOOKED', 'Booked')], default='HELD', max_length=10)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.showtime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
