# Generated by Django 6.0.7 on 2026-08-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_showtime_date_remove_showtime_theater_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='screen_name',
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_rows', models.IntegerField(default=4, help_text='e.g., 4 creates rows A, B, C, D')),
                ('seats_per_row', models.IntegerField(default=8, help_text='Number of seats in each row')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theater')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seat',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.screen'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('screen', 'row', 'number')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='screen_name',
        ),
    ]
