# Generated by Django 6.0.7 on 2026-08-19 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_trailer_url',
            field=models.URLField(help_text='YouTube URL or Embed ID', validators=[django.core.validators.RegexValidator(message='Enter a valid YouTube URL', regex='^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.?be)\\/.+$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='status',
            field=models.CharField(choices=[('HELD', 'Temporarily Held'), ('BOOKED', 'Booked')], db_index=True, default='HELD', max_length=10),
        ),
    ]
